'use strict';

module.exports = [
    './gulp/tasks/serve.js',
    './gulp/tasks/watch.js',
    './gulp/tasks/clean.js',
    './gulp/tasks/svg.js',
    './gulp/tasks/pug.js',
    './gulp/tasks/sass.js',
    './gulp/tasks/img.js',
    './gulp/tasks/scripts.js',
    './gulp/tasks/fonts.js',
    './gulp/tasks/fontsConvert.js',
    './gulp/tasks/jsPlugins.js',
    './gulp/tasks/plugins/fontAwesome.js',
    './gulp/tasks/plugins/style/normalize.js',
    './gulp/tasks/plugins/style/bootstrap4.js',
    './gulp/tasks/plugins/js/bootstrap4js.js',
    './gulp/tasks/plugins/js/jQuery.js',
    './gulp/tasks/plugins/js/tether.js',
    './gulp/tasks/plugins/js/countrySelect.js',
    './gulp/tasks/plugins/style/countrySelect.js',
    './gulp/tasks/plugins/style/countrySelectImg.js',
    './gulp/tasks/plugins/js/airDatepicker.js',
    './gulp/tasks/plugins/style/airDatepicker.js',
];